DOCK_ROOT 	      = /HOME/nscc-gz_pinchen/compute/bin/vina_wrapper
universe                = vanilla 
executable              = $(DOCK_ROOT)/vina_dock
arguments               = "a053 zinc_Pur1000w_sort_heavy zinc_a053 zinc_Pur1000w_sort_heavy_a053 5f5w"
log                     = /HOME/nscc-gz_pinchen/compute/condor/a053/dock.log 
output                  = /HOME/nscc-gz_pinchen/compute/condor/a053/output.txt
error                   = /HOME/nscc-gz_pinchen/compute/condor/a053/errors.txt
should_transfer_files   = IF_NEEDED
when_to_transfer_output = ON_EXIT
environment             = "LD_LIBRARY_PATH=/HOME/nscc-gz_pinchen/compute/bin/vina_wrapper/lib:/WORK/app/Openbabel/2.3.2-python/lib:$LD_LIBRARY_PATH"  
queue 16000
