DOCK_ROOT 	      = /HOME/nscc-gz_pinchen/compute/bin/babel_wrapper
universe                = vanilla 
executable              = $(DOCK_ROOT)/babel_wrapper
arguments               = "a096 zinc_ligand_100w_sort zinc_a096 zinc_ligand_100w_sort_a096 5f5w"
log                     = /HOME/nscc-gz_pinchen/compute/condor/a096/dock.log 
output                  = /HOME/nscc-gz_pinchen/compute/condor/a096/output.txt
error                   = /HOME/nscc-gz_pinchen/compute/condor/a096/errors.txt
should_transfer_files   = IF_NEEDED
when_to_transfer_output = ON_EXIT
environment             = "LD_LIBRARY_PATH=/HOME/nscc-gz_pinchen/compute/bin/vina_wrapper/lib:/WORK/app/Openbabel/2.3.2-python/lib:$LD_LIBRARY_PATH"  
queue 100
