DOCK_ROOT 	      = /HOME/nscc-gz_pinchen/compute/bin/vina_wrapper
universe                = vanilla 
executable              = $(DOCK_ROOT)/vina_dock
arguments               = "a015 zinc_Purt10w_sort zinc_a015 zinc_Purt10w_sort_a015 5f5w"
log                     = /HOME/nscc-gz_pinchen/compute/condor/a015/dock.log 
output                  = /HOME/nscc-gz_pinchen/compute/condor/a015/output.txt
error                   = /HOME/nscc-gz_pinchen/compute/condor/a015/errors.txt
should_transfer_files   = IF_NEEDED
when_to_transfer_output = ON_EXIT
environment             = "LD_LIBRARY_PATH=/HOME/nscc-gz_pinchen/compute/bin/vina_wrapper/lib:/WORK/app/Openbabel/2.3.2-python/lib:$LD_LIBRARY_PATH"  
queue 8000
