WEGA_ROOT 	      = /HOME/nscc-gz_pinchen/compute/bin/wega_wrapper 
universe                = vanilla 
executable              = $(WEGA_ROOT)/wega_wrapper
arguments               = "a076 zinc_conformer_100w zinc_a076 zinc_conformer_100w_a076 oneQuery.sd"
log                     = /HOME/nscc-gz_pinchen/compute/condor/a076/dock.log 
output                  = /HOME/nscc-gz_pinchen/compute/condor/a076/output.txt
error                   = /HOME/nscc-gz_pinchen/compute/condor/a076/errors.txt
should_transfer_files   = IF_NEEDED
when_to_transfer_output = ON_EXIT
environment             = "LD_LIBRARY_PATH=/HOME/nscc-gz_pinchen/compute/bin/wega_wrapper/lib:$LD_LIBRARY_PATH"  
queue 240
