DOCK_ROOT 	      = /HOME/nscc-gz_pinchen/compute/bin/vina_wrapper
universe                = vanilla 
executable              = $(DOCK_ROOT)/vina_dock_time
arguments               = "a009 zinc_10w zinc_a009 zinc_10w_a009 5f5w"
log                     = /HOME/nscc-gz_pinchen/compute/condor/a009/dock.log 
output                  = /HOME/nscc-gz_pinchen/compute/condor/a009/output.txt
error                   = /HOME/nscc-gz_pinchen/compute/condor/a009/errors.txt
should_transfer_files   = IF_NEEDED
when_to_transfer_output = ON_EXIT
environment             = "LD_LIBRARY_PATH=/HOME/nscc-gz_pinchen/compute/bin/vina_wrapper/lib:/WORK/app/Openbabel/2.3.2-python/lib:$LD_LIBRARY_PATH"  
queue 8000
