WEGA_ROOT 	      = /HOME/nscc-gz_pinchen/compute/bin/wega_wrapper 
universe                = vanilla 
executable              = $(WEGA_ROOT)/wega_wrapper
arguments               = "a077 zinc_conformer_all zinc_a077 zinc_conformer_all_a077 oneQuery.sd"
log                     = /HOME/nscc-gz_pinchen/compute/condor/a077/dock.log 
output                  = /HOME/nscc-gz_pinchen/compute/condor/a077/output.txt
error                   = /HOME/nscc-gz_pinchen/compute/condor/a077/errors.txt
should_transfer_files   = IF_NEEDED
when_to_transfer_output = ON_EXIT
environment             = "LD_LIBRARY_PATH=/HOME/nscc-gz_pinchen/compute/bin/wega_wrapper/lib:$LD_LIBRARY_PATH"  
queue 1000
