DOCK_ROOT 	      = /HOME/nscc-gz_pinchen/compute/bin/vina_wrapper
universe                = vanilla 
executable              = $(DOCK_ROOT)/vina_dock_time
arguments               = "a007 zinc_Pur1w zinc_a007 zinc_Pur1w_a007 5f5w"
log                     = /HOME/nscc-gz_pinchen/compute/condor/a007/dock.log 
output                  = /HOME/nscc-gz_pinchen/compute/condor/a007/output.txt
error                   = /HOME/nscc-gz_pinchen/compute/condor/a007/errors.txt
should_transfer_files   = IF_NEEDED
when_to_transfer_output = ON_EXIT
environment             = "LD_LIBRARY_PATH=/HOME/nscc-gz_pinchen/compute/bin/vina_wrapper/lib:/WORK/app/Openbabel/2.3.2-python/lib:$LD_LIBRARY_PATH"  
queue 1000
