DOCK_ROOT 	      = /HOME/nscc-gz_pinchen/compute/bin/vina_wrapper
universe                = vanilla 
executable              = $(DOCK_ROOT)/vina_dock
arguments               = "a038 zinc_Pur10w_sort_heavy zinc_a038 zinc_Pur10w_sort_heavy_a038 5f5w"
log                     = /HOME/nscc-gz_pinchen/compute/condor/a038/dock.log 
output                  = /HOME/nscc-gz_pinchen/compute/condor/a038/output.txt
error                   = /HOME/nscc-gz_pinchen/compute/condor/a038/errors.txt
should_transfer_files   = IF_NEEDED
when_to_transfer_output = ON_EXIT
environment             = "LD_LIBRARY_PATH=/HOME/nscc-gz_pinchen/compute/bin/vina_wrapper/lib:/WORK/app/Openbabel/2.3.2-python/lib:$LD_LIBRARY_PATH"  
queue 2000
