DOCK_ROOT 	      = /HOME/nscc-gz_pinchen/compute/bin/vina_wrapper
universe                = vanilla 
executable              = $(DOCK_ROOT)/vina_dock
arguments               = "a028 zinc_Pur100w_sort zinc_a028 zinc_Pur100w_sort_a028 5f5w"
log                     = /HOME/nscc-gz_pinchen/compute/condor/a028/dock.log 
output                  = /HOME/nscc-gz_pinchen/compute/condor/a028/output.txt
error                   = /HOME/nscc-gz_pinchen/compute/condor/a028/errors.txt
should_transfer_files   = IF_NEEDED
when_to_transfer_output = ON_EXIT
environment             = "LD_LIBRARY_PATH=/HOME/nscc-gz_pinchen/compute/bin/vina_wrapper/lib:/WORK/app/Openbabel/2.3.2-python/lib:$LD_LIBRARY_PATH"  
queue 16000
