DOCK_ROOT 	      = /HOME/nscc-gz_pinchen/compute/bin/babel_wrapper
universe                = vanilla 
executable              = $(DOCK_ROOT)/babel_wrapper
arguments               = "a117 zinc_ligand_all zinc_a117 zinc_ligand_all_a117 5f5w"
log                     = /HOME/nscc-gz_pinchen/compute/condor/a117/dock.log 
output                  = /HOME/nscc-gz_pinchen/compute/condor/a117/output.txt
error                   = /HOME/nscc-gz_pinchen/compute/condor/a117/errors.txt
should_transfer_files   = IF_NEEDED
when_to_transfer_output = ON_EXIT
environment             = "LD_LIBRARY_PATH=/HOME/nscc-gz_pinchen/compute/bin/vina_wrapper/lib:/WORK/app/Openbabel/2.3.2-python/lib:$LD_LIBRARY_PATH"  
queue 1600
